#!/usr/bin/python3

from fillpdf import fillpdfs

import sys
import os


# Set the returned dictionary values a save to a variable
# For radio boxes ('Off' = not filled, 'Yes' = filled)



codigo_ciclo="IFCS01"
codigo_modulo="0369"

data_dict = {
'Grupo':'Administración de Sistemas Informáticos en Red',
'Grupo_2':'1º ASIR',
'Curso académico':'2024/2025',
'Año escolar':'2025',
'NO':'Implantación de Sistemas Informáticos',
}


def genera_plantilla(base,salida):
    fillpdfs.write_fillable_pdf(base,salida, data_dict)


def genera_anexo(nombre,plantilla):
    fichero="_{0}_{1}_ANEXOI.pdf".format(codigo_ciclo,codigo_modulo)
    fichero=nombre.replace("á","a").replace("é","e").replace("í","i").replace("ó","o").replace("ú","u").replace("ñ","n").replace(" ","_")+fichero
    data_dict['Alumnoa']=nombre

    fillpdfs.write_fillable_pdf('plantilla-anexito.pdf', "./anexos/"+fichero, data_dict)


if __name__=='__main__':

    if (len(sys.argv)<2):
        print ("Faltan argumentos")
        sys.exit(0)

    if (sys.argv[1] == "-l"):
        fillpdfs.print_form_fields("plantilla-anexito.pdf")
        sys.exit(0)

    if (sys.argv[1] == "-t"):
        genera_plantilla("formulario.pdf","plantilla.pdf")
        sys.exit(0)

    if (sys.argv[1] == "-p"):
        os.makedirs("anexos", exist_ok = True)
        with open('nombres.txt') as f:
            for nombre in f:
                nombre=nombre.replace("\n","")
                if len(nombre)>0:
                    print ("Genero anexo para "+nombre)
                    genera_anexo(nombre,"plantilla-anexito.pdf")
        sys.exit(0)

    print ("Argumentos  erróneos")





